stages:
  - build
  - run
  - test

variables:
  ANALYSIS_TOP_VERSION: 21.2.19
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"
  PACKAGE_NAME: ttHMultiAna
  SRC_DIR_ABS: "${CI_PROJECT_DIR}/${SRC_DIR}"
  BUILD_DIR: myBuild
  RUN_DIR: myRun

.analysis_image: &image
  image: lukasheinrich/recast_cvmfs_assisted:20161231
  tags:
    - cvmfs
  before_script:
    - pwd
    - ls
    - echo "Project Directory    ${CI_PROJECT_DIR}"
    - echo "Build Directory      ${BUILD_DIR}"
    - echo "Run Directory        ${RUN_DIR}"
#    - echo $SERVICE_PASS | kinit $CERN_USER
.run_template: &run
  <<: *image
  stage: run
  dependencies: [build]
  script:
    - pwd
    - cd 
    - ls
    - set +e
    - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
    - asetup AnalysisTop,${ANALYSIS_TOP_VERSION},here
    - source ${BUILD_DIR}/*/setup.sh
    - mkdir $RUN_DIR
    - cd $RUN_DIR
    - ls
    - cp $CI_PROJECT_DIR/share/${config_file} . 
    - echo xrdfs ${eos_file} > infile_tth.txt 
    - top-xaod ${config_file}  infile_tth.txt

    
build:
  <<: *image
  stage: build
  script:
    - cd 
    - mkdir $BUILD_DIR
    - set +e
    - cd $BUILD_DIR
    - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
    - asetup AnalysisTop,${ANALYSIS_TOP_VERSION},here
    - cp CMakeLists.txt $CI_PROJECT_DIR/../
    - cmake $CI_PROJECT_DIR/../
    - cmake --build ./
  artifacts:
    paths:
      - $BUILD_DIR
    name: "${BUILD_DIR}_${CI_JOB_NAME}"
    expire_in: 1d
  tags:
    - cvmfs
    
run_ttbar:
  <<: *run
  variables: 
    eos_file: root://eosuser.cern.ch//eos/user/n/narayan/tthml_ci/DAOD_HIGG8D1/mc16_13TeV:DAOD_HIGG8D1.12726347._001270.pool.root.1
    config_file: generic_config_mc16c.txt
    
run_data:
  <<: *run
  variables:
    eos_file: root://eosuser.cern.ch//eos/user/n/narayan/tthml_ci/DAOD_HIGG8D1/data_17_13TeV:DAOD_HIGG8D1.12825536._000052.pool.root.1
    config_file: generic_config-data.txt
    


