stages:
  - build
  - run
  - test

variables:
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"
  PACKAGE_NAME: ttHMultiAna
  SRC_DIR_ABS: "${CI_PROJECT_DIR}/${SRC_DIR}"
  BUILD_DIR: myBuild
  RUN_DIR: myRun

.analysis_image: &image
  image: lukasheinrich/recast_cvmfs_assisted:20161231
  tags:
    - cvmfs
  before_script:
    - pwd
    - ls
    - echo "Project Directory    ${CI_PROJECT_DIR}"
    - echo "Source Directory     ${SRC_DIR_ABS}"
    - echo "      Directory Name ${SRC_DIR}"
    - echo "Build Directory      ${BUILD_DIR_ABS}"
    - echo "      Directory Name ${BUILD_DIR}"
#    - echo $SERVICE_PASS | kinit $CERN_USER
    
build:
  <<: *image
  stage: build
  script:
    - cd 
    - mkdir $BUILD_DIR
    - set +e
    - cd $BUILD_DIR
    - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
    - asetup AnalysisTop,21.2.19,here
    - cp CMakeLists.txt $CI_PROJECT_DIR/../
    - cmake $CI_PROJECT_DIR/../
    - cmake --build ./
  artifacts:
    paths:
      - $BUILD_DIR
    name: "${BUILD_DIR}_${CI_JOB_NAME}"
    expire_in: 1d
  tags:
    - cvmfs
    
.run_template: &run
  <<: *image
  stage: run
  dependencies: [build]
  script:
    - cd 
    - set +e
    - source ${BUILD_DIR}/*/setup.sh
    - mkdir $RUN_DIR
    - cd $RUN_DIR
    - cp $CI_PROJECT_DIR/../ttHMultiAna/share/generic_config_mc16c.txt . 
    - echo xrdfs root://eosuser.cern.ch//eos/user/n/narayan/tthml_ci/DAOD_HIGG8D1/mc16_13TeV:DAOD_HIGG8D1.12726347._001270.pool.root.1 > infile_tth.txt 
    - top-xaod generic_config_mc16c.txt infile_htop.txt


