stages:
  - build
  - run
  - test

variables:
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"
  PACKAGE_NAME: ttHMultiAna
  SRC_DIR_ABS: "${CI_PROJECT_DIR}/${SRC_DIR}"
  BUILD_DIR_ABS: "${CI_PROJECT_DIR}/${BUILD_DIR}"

.analysis_image: &image
  image: lukasheinrich/recast_cvmfs_assisted:20161231
  tags:
    - cvmfs
  before_script:
    - pwd
    - ls
    - echo "Project Directory    ${CI_PROJECT_DIR}"
    - echo "Source Directory     ${SRC_DIR_ABS}"
    - echo "      Directory Name ${SRC_DIR}"
    - echo "Build Directory      ${BUILD_DIR_ABS}"
    - echo "      Directory Name ${BUILD_DIR}"
#    - echo $SERVICE_PASS | kinit $CERN_USER
    
build:
  <<: *image
  stage: build
  script:
    - cd 
    - mkdir myBuild
    - set +e
    - cd myBuild
    - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
    - asetup AnalysisTop,21.2.19,here
    - cp CMakeLists.txt $CI_PROJECT_DIR/../
    - cmake $CI_PROJECT_DIR/../
    - cmake --build ./
    - cd ../
  artifacts:
    paths:
      - $BUILD_DIR
    name: "${BUILD_DIR}_${CI_JOB_NAME}"
    expire_in: 1d
  tags:
    - cvmfs
    


