stages:
  - build
  - run
  - test

variables:
  ANALYSIS_TOP_VERSION: 21.2.19
  ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"
  PACKAGE_NAME: ttHMultiAna
  SRC_DIR: source
  BUILD_DIR: build
  RUN_DIR: run
  SRC_DIR_ABS: "${CI_PROJECT_DIR}/${SRC_DIR}"
  BUILD_DIR_ABS: "${CI_PROJECT_DIR}/${BUILD_DIR}"
  RUN_DIR_ABS: "${CI_PROJECT_DIR}/${RUN_DIR}"

.analysis_image: &image
  image: lukasheinrich/recast_cvmfs_assisted:20161231
  tags:
    - cvmfs
  before_script:
    - pwd
    - cd ../
    - mv $PACKAGE_NAME /tmp/$PACKAGE_NAME 
    - mkdir -p $SRC_DIR_ABS
    - mv /tmp/$PACKAGE_NAME $SRC_DIR_ABS #Need to reorganize the source
    - ls $SRC_DIR_ABS
    - echo "Project Directory    ${CI_PROJECT_DIR}"
    - echo "Source Directory     ${SRC_DIR_ABS}"
    - echo "      Directory Name ${SRC_DIR}"
    - echo "Build Directory      ${BUILD_DIR_ABS}"
    - echo "      Directory Name ${BUILD_DIR}"
    - echo $TTHML_PASSWD | kinit $TTHML_USER 
    
.run_template: &run
  <<: *image
  stage: run
  dependencies: [build]
  script:
    - pwd
    - ls
    - set +e
    - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
    - asetup AnalysisTop,${ANALYSIS_TOP_VERSION},here
    - ls ${BUILD_DIR}/
    - source ${BUILD_DIR_ABS}/${AnalysisTop_PLATFORM}/setup.sh
    - cd
    - mkdir $RUN_DIR_ABS
    - cd $RUN_DIR_ABS
    - ls
    - cp ${SRC_DIR_ABS}/share/${config_file} . 
    - echo xrdfs ${eos_file} > infile_tth.txt 
    - top-xaod ${config_file}  infile_tth.txt

    
build:
  <<: *image
  stage: build
  script:
    - mkdir $BUILD_DIR_ABS
    - set +e
    - cd $BUILD_DIR_ABS
    - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
    - asetup AnalysisTop,${ANALYSIS_TOP_VERSION},here
    - cp CMakeLists.txt $SRC_DIR_ABS
    - cmake $SRC_DIR_ABS
    - cmake --build ./
    - cd ../
    - source $BUILD_DIR_ABS/${AnalysisTop_PLATFORM}/setup.sh
    - pwd 
    - ls 
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 2h
  tags:
    - cvmfs
    
run_ttbar:
  <<: *run
  variables: 
    eos_file: root://eosuser.cern.ch//eos/user/n/narayan/tthml_ci/DAOD_HIGG8D1/mc16_13TeV:DAOD_HIGG8D1.12726347._001270.pool.root.1
    config_file: generic_config_mc16c.txt
    
run_data:
  <<: *run
  variables:
    eos_file: root://eosuser.cern.ch//eos/user/n/narayan/tthml_ci/DAOD_HIGG8D1/data_17_13TeV:DAOD_HIGG8D1.12825536._000052.pool.root.1
    config_file: generic_config-data.txt
    


